//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hand
    {
        public Hand()
        {
            this.Plays = new HashSet<Plays>();
            this.Further = new HashSet<Furthers>();
            this.PlayedOn = new HashSet<PlayedOn>();
        }
    
        public long HandId { get; set; }
        public decimal PotSize { get; set; }
        public int ButtonPosition { get; set; }
        public System.DateTime Time { get; set; }
        public int NumberOfPlayers { get; set; }
        public string RiverCard { get; set; }
        public string TurnCard { get; set; }
        public string FlopCard3 { get; set; }
        public string FlopCard2 { get; set; }
        public string FlopCard1 { get; set; }
    
        public virtual ICollection<Plays> Plays { get; set; }
        public virtual ICollection<Furthers> Further { get; set; }
        public virtual ICollection<PlayedOn> PlayedOn { get; set; }
    }
}
