//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandAction
    {
        public HandAction()
        {
            this.Furthers = new HashSet<Furthers>();
            this.Performs = new HashSet<Performs>();
        }
    
        public long ActionID { get; set; }
        public string ActionName { get; set; }
        public string Street { get; set; }
        public long Amount { get; set; }
        public byte[] IsPFR { get; set; }
        public byte[] IsVPIP { get; set; }
        public long HandHandId { get; set; }
    
        public virtual ICollection<Furthers> Furthers { get; set; }
        public virtual ICollection<Performs> Performs { get; set; }
    }
}
