//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plays
    {
        public string HoleCard1 { get; set; }
        public string HoleCard2 { get; set; }
        public decimal StartingStack { get; set; }
        public decimal EndingStack { get; set; }
        public int SeatPosition { get; set; }
        public long HandId { get; set; }
        public string Name { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Hand Hand { get; set; }
    }
}
