//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Performs = new HashSet<Performs>();
            this.Plays = new HashSet<Plays>();
        }
    
        public string Winnings { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Performs> Performs { get; set; }
        public virtual ICollection<Plays> Plays { get; set; }
    }
}
