//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayedOn
    {
        public long HandId { get; set; }
        public string TableID { get; set; }
    
        public virtual Table Table { get; set; }
        public virtual Hand Hand { get; set; }
    }
}
