//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Poker_x0020_ModelContainer : DbContext
    {
        public Poker_x0020_ModelContainer()
            : base("name=Poker_x0020_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Hand> Hands { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<HandAction> HandActions { get; set; }
        public virtual DbSet<Plays> Plays { get; set; }
        public virtual DbSet<Furthers> Furthers1 { get; set; }
        public virtual DbSet<PlayedOn> PlayedOns { get; set; }
        public virtual DbSet<Performs> Performs { get; set; }
    }
}
